sessionStorage:
  type: redis
  redis:
    clientType: sentinel
    sentinel:
      password: "foo"
      masterName: "mymaster"
      connectionUrls: "redis://oauth2-proxy-redis:26379,redis://oauth2-proxy-redis:26379"

# provision an instance of the redis-ha sub-chart
redis:
  enabled: true
  fullnameOverride: oauth2-proxy-redis
  replicas: 3
  redisPassword: "foo"
  redis:
    masterGroupName: mymaster

initContainers:
  waitForRedis:
    enabled: true
