sessionStorage:
  type: redis
  redis:
    clientType: "standalone"
    password: "foo"

# provision an instance of the redis-ha sub-chart
redis:
  enabled: true
  fullnameOverride: oauth2-proxy-redis
  replicas: 1
  redisPassword: "foo"

initContainers:
  waitForRedis:
    enabled: true
