extraEnv:
  - name: TEST_ENV_VAR_2
    value: '{{ $.Release.Name }}'
ingress:
  enabled: true
  hosts:
    - "{{ $.Release.Name }}.local"
  tls:
    - hosts:
        - "{{ $.Release.Name }}.local"
  annotations:
    test: "{{ $.Release.Name }}"
oauth2-proxy:
  checkDeprecation: false
  config:
    clientSecret: '{{ $.Release.Name }}'
    configFile: |
      oidc_issuer_url = "https://{{ $.Release.Name }}/dex"

pass_authorization_header: "true"

extraArgs:
  pass-authorization-header: "{{ $.Values.pass_authorization_header }}"

extraVolumes:
  - name: "{{ $.Release.Name }}-secret"
    secret:
      secretName: "{{ .Release.Name }}-secret"
      items:
        - key: secret
          path: secret

authenticatedEmailsFile:
  annotations:
    test: "{{ $.Release.Name }}"

config:
  annotations:
    test: "{{ $.Release.Name }}"

deploymentAnnotations:
  test: "{{ $.Release.Name }}"

autoscaling:
  annotations:
    test: "{{ $.Release.Name }}"

alphaConfig:
  annotations:
    test: "{{ $.Release.Name }}"

service:
  annotations:
    test: "{{ $.Release.Name }}"

serviceAccount:
  annotations:
    test: "{{ $.Release.Name }}"

serviceMonitor:
  annotations:
    test: "{{ $.Release.Name }}"
