{{- if and .Values.config.google (not .Values.config.google.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-google
type: Opaque
data:
  service-account.json: {{ .Values.config.google.serviceAccountJson | b64enc | quote }}
{{- end -}}
