{{- if and .Values.podDisruptionBudget.enabled (gt (.Values.replicaCount | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "oauth2-proxy.name" . }}
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
