{{- $name := include "oauth2-proxy.name" .  -}}
{{- $fullName := include "oauth2-proxy.fullname" .  -}}
{{- $labels := include "oauth2-proxy.labels" . -}}
{{- with .Values.sessionStorage }}
{{- if and (eq .type "redis") (not .redis.existingSecret) (or .redis.password .redis.sentinel.password) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ $name }}
    {{- $labels | indent 4 }}
  name: {{ $fullName }}-redis-access
type: Opaque
data:
  {{- with .redis.password }}
  redis-password: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .redis.sentinel.password }}
  redis-sentinel-password: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
