name: Bump Chart Version

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  bump-version:
    if: "!contains(github.actor, 'oauth2-proxy-bot')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ssh-key: "${{ secrets.PUSH_KEY }}"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "oauth2-proxy-bot"
          git config user.email "oauth2-proxy-bot@users.noreply.github.com"

      - name: Bump Chart Version
        uses: GarnerCorp/build-actions/bump-version@ed29b86d30dadb5912f0ec45dc3a0c3ca0148826 # main
        with:
          version-file-path: helm/oauth2-proxy/Chart.yaml
          version-parser: scripts/chart-version-parser.py
          git-name: "oauth2-proxy-bot"
          git-email: "oauth2-proxy-bot@users.noreply.github.com"
          major: changelogs/major
          minor: changelogs/minor
